### ISSUE TITLE
require() of ES Module not supported

### ISSUE THREAD

**Issue by tinythomasffm** [BlueAndi/niu-cloud-cli#8]
When building with a current node Docker image, I got the following error:

```
/opt/niu-cloud-cli/libs/niu-cloud-connector/index.js:25
var got = require("got");
          ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/niu-cloud-cli/node_modules/got/dist/source/index.js from /opt/niu-cloud-cli/libs/niu-cloud-connector/index.js not supported.
Instead change the require of /opt/niu-cloud-cli/node_modules/got/dist/source/index.js in /opt/niu-cloud-cli/libs/niu-cloud-connector/index.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/opt/niu-cloud-cli/libs/niu-cloud-connector/index.js:25:11) {
  code: 'ERR_REQUIRE_ESM'
}
```

This can be fixed by changing the above require to ```import got from 'got';``` and adding ```"type": "module",``` to package.json.

However, the same error happens after that with ```require("yargs");``` from niu-cloud-cli.js. Changing that to the import syntax then leads to a bunch of errors from yarn that are above my (very limited) js knowledge:

````
file:///opt/niu-cloud-cli/niu-cloud-cli.js:30
    .command(require("./src/createToken"))
    ^

ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/opt/niu-cloud-cli/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///opt/niu-cloud-cli/niu-cloud-cli.js:30:5
    at ModuleJob.run (node:internal/modules/esm/module_job:218:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:329:24)
    at async loadESM (node:internal/process/esm_loader:28:7)
    at async handleMainPromise (node:internal/modules/run_main:113:12)

```

**Comment by BlueAndi** [comment]
Can you please check the development branch, its already updated.
https://github.com/BlueAndi/niu-cloud-cli/tree/development
